dist: bionic
language: node_js
node_js:
 - "node"
cache:
  directories:
    - node_modules
install:
  - npm install
  - python3 --version
  - sudo apt-get install -y python3-pip
  - sudo apt-get install -y python3-setuptools
  - pip3 --version
  - pip3 install mitmproxy
script:
  - npm test
