language: node_js
node_js:
 - "node"
cache:
  directories:
    - node_modules
install:
  - npm install
  - add-apt-repository -y ppa:jonathonf/python-3.6
  - apt-get update
  - apt-get install -y python3.6 python3-pip
  - python3 --version
  - pip3 --version
script:
  - npm test