dist: bionic
language: node_js
node_js:
 - "node"
cache:
  directories:
    - node_modules
install:
  - npm install
  - python3 --version
  - sudo apt-get install python3-pip
  - pip3 --version
script:
  - npm test